### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by aharoun** [aharoun/AAABK2018.jl#1]
- [x] Use gauss method for integration (interpolating solution to diff equations will be faster if you supply the whole array of values)
- [x] Solve the differential equations in one step
- [x] Diff eq solutions produce some volatility close to zero which in turn may affect integration. Deal with it.
